services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zelos
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql

volumes:
  database: