import '@/public/css/globals.css';

export const metadata = {
	favicon: '/favicon.ico',
	title: 'Suporte Técnico - SENAI',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="pt-br"
			data-lt-installed='suppresshydrationwarning="true" - data-lt-installed="true"'
		>
			<body cz-shortcut-listen="true" className="bg-zinc-800 font-inter">
				{children}
			</body>
		</html>
	);
}
