import "@/public/css/globals.css";
import Header from "./components/Header/Header";

export const metadata = {
  favicon: '/favicon.ico',
  title: "Suporte Técnico - SENAI",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" >
      <body cz-shortcut-listen="true" className="bg-zinc-800 font-inter">
        <Header/>
        {children}
      </body>
    </html>
  );
}
