import "@/public/css/globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body cz-shortcut-listen="true">
        <Header />
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
